### ISSUE TITLE
Which launch file of SC-PGO should be used

### ISSUE THREAD

**Issue by CharlieV5** [lian-yue0515/MM-LINS#1]
Hi！
I download your indoor test data in baidu cloud and find that they are Livox LiDAR data. Which launch file should be used , since there are no livox launch file for SC-PGO?
![image](https://github.com/lian-yue0515/MM-LINS/assets/8245892/edcd9365-0d62-401e-bfac-7deebfa4eb30)
And, there's something wrong with Factory-2.bag and Factory-3.bag.
![image](https://github.com/lian-yue0515/MM-LINS/assets/8245892/3498d67d-7f29-47a6-97e6-ed7732d42d20)

**Comment by lian-yue0515** [comment]
1. SC-PGO is a standalone node, just run roslaunch aloam_velodyne fastlio_ouster64.launch
2. There may be a problem with the transfer of the dataset, which will be corrected in the future
