### ISSUE TITLE
关于sleep map与active map的融合

### ISSUE THREAD

**Issue by supersupercoconut** [lian-yue0515/MM-LINS#2]
感谢您的论文与代码 ！我目前在阅读您的论文时发现，如果检测到退化环境，系统是会将当前的Map转换成为sleep map，然后不断地尝试动态初始化，直到离开退化场景。之后会按照动态初始化的结果，重新开始建图，即active map。但是这里sleep map与active map之间的区域是不是就没有建图与里程计数据。后续的优化部分感觉只是对sleep map与active map中的相似部分进行判断，即执行回环检测，没有补充这部分的轨迹。我的疑惑就是这部分的轨迹最终是如何生成的呢，就是退化场景的建图与里程计是哪部分生成的呢？
    期待您的回复，祝您工作顺利！

**Comment by lian-yue0515** [comment]
首先感谢你的关注，对于您“退化场景的建图与里程计是如何生成的？”问题，对于这个区域的地图理论上是无法生成的，因为这部分点云数据是退化的，轨迹可以考虑短暂记录imu数据加以约束（但是如果退化时间过长imu数据的积分也是不可靠的）。但是在本工作中，这部分是默认不考虑的，因为这部分区域对于本工作而言是无用的。

**Comment by supersupercoconut** [comment]
感谢您的即时回复。
但是我看您的论文中的Fig.1中在退化环境中依然可以生成轨迹，我一开始认为这部分是SC-PGO部分中优化得出来的结果，后来继续阅读感觉PGO只是一种位姿优化器，在检测到回环之后进行两个地图位姿之间的优化。不过我现在了解这部分的实现了。
再次感谢您的回复！
![2024-07-08_15-52](https://github.com/lian-yue0515/MM-LINS/assets/137087582/0ef099ad-8910-4b44-bf51-e4bc46e0a80c)

**Comment by lian-yue0515** [comment]
没问题，有疑惑尽管提问就好
