### ISSUE TITLE
active map and sleeping map 

### ISSUE THREAD

**Issue by silent-zhou** [lian-yue0515/MM-LINS#3]
非常感谢您的代码和论文，有几个问题想请教一下：
1.检测退化场景后，active map保存至sleeping map并重新创建new map，那请问这个new map的基准参考坐标系是否与sleeping map 的基准坐标系一致？ 是重新从退化那一帧重置为（0，0，0）开始，还是以退化那一帧相对W系的坐标呢？（我在代码IMU_init_dynamic函数中，并没有看到kf_point的pose被使用）
![image](https://github.com/user-attachments/assets/982d03db-d1ee-4688-9fa5-6364bd0a10b5)

2.有个疑问的地方时，论文中说退化后需要重新初始化，那在图1退化的这段时间内，lidar测量退化求出的odom_pose也是不准的，那动态初始化结果会准确？（代码中的IMU_init_dynamic目前好像和静态初始化没有区别）
还有就是退化距离长达20m左右，这里的IMU航迹推算这么准确吗？
![image](https://github.com/user-attachments/assets/25554846-e8d1-43da-a5a9-7c3e5acb38d6)

**Comment by lian-yue0515** [comment]
感谢您的关注，对于问题1：new map的基准参考坐标系是在离开退化区域时刻开始以（0，0，0）开始的；对于问题2：①动态初始化部分确实没有开源，您可以持续关注我的相关工作，②imu退化期间不会持续使用IMU航迹推算，问题2可能有相关解答。

**Comment by silent-zhou** [comment]
非常感谢您的回复！
1.对于问题1，我已经明白，也就是该方法必须要出现相似场景，才能使两个map合并到统一基准坐标系

对于问题2中的，我还是比较好奇退化后里程计轨迹如何支撑到lidar的有效观测，期待您的相关解答，谢谢~~！！

**Comment by lian-yue0515** [comment]
你可以参考https://github.com/lian-yue0515/MM-LINS/issues/2#issuecomment-2213260012，可能会解答你的问题

**Comment by silent-zhou** [comment]
好的，了解了，多谢~

**Comment by maomao0220** [comment]
您好，请问动态初始化部分开源了吗？ @lian-yue0515 @silent-zhou

**Comment by chairc** [comment]
> 您好，请问动态初始化部分开源了吗？ [@lian-yue0515](https://github.com/lian-yue0515) [@silent-zhou](https://github.com/silent-zhou)

https://github.com/lian-yue0515/D-LI-Init
