### ISSUE TITLE
Something wrong with the README.md

### ISSUE THREAD

**Issue by Gatsby23** [lian-yue0515/MM-LINS#4]
Nice work, but there are something wrong with the readme.
```
Citation
If you use PIN-SLAM for any academic work, please cite our original [paper](https://ieeexplore.ieee.org/document/10557776)
```
Maybe you should correct the 'PIN-SLAM' as 'MM-LINS' and hope you have a great improvement on the implicit map.

**Comment by lian-yue0515** [comment]
thanks, it was my negligence that caused the ridiculous problem. I've made corrections.
